### ISSUE TITLE
Examples links are returning an Error

### ISSUE THREAD

**Issue by mindprocessor** [jaxon-php/jaxon-core#108]
hi, the links under examples are returning an error, or because these are for version 2 and does not have any connection with the current one?

error : Call to undefined function html5qp()

**Comment by feuzeu** [comment]
Hi,

The examples still need to be upgraded to the latest version.
Sorry for the convenience.

For now, you can check the demo integration packages, and ask any question.
- Symfony: https://github.com/jaxon-php/jaxon-demo-symfony
- Laravel: https://github.com/jaxon-php/jaxon-demo-laravel
- CakePHP: https://github.com/jaxon-php/jaxon-demo-cakephp
- Slim: https://github.com/jaxon-php/jaxon-demo-slim
- Yii: https://github.com/jaxon-php/jaxon-demo-yii
- CodeIgniter: https://github.com/jaxon-php/jaxon-demo-codeigniter

**Comment by scottcwilson** [comment]
This is still an issue.  Can you fix?  I'm coming from Xajax.

**Comment by feuzeu** [comment]
Hi,

I think I'll simply deprecate these examples.
Jaxon has been forked from Xajax for too long now, and I do not recommend using it the Xajax way anymore.

So, you'll need an extra effort to upgrade to Jaxon. That means at least:
- Have a single entry point in your application to process all Jaxon requests: https://www.jaxon-php.org/docs/v4x/requests/processing.html.
- Register namespaces, instead of functions or classes: https://www.jaxon-php.org/docs/v4x/registrations/namespaces.html. Make sure your namespaces are registered with autoloading.
- Bootstrap the Jaxon library from a config file: https://www.jaxon-php.org/docs/v4x/features/bootstrap.html.

Optionally, you can check the `Application features` and `Annotations` section in the documentation https://www.jaxon-php.org/docs/v4x.html to see more features.

There are also some real world open source applications that are using Jaxon.

#### A Supervisor dashboard

https://github.com/lagdo/jaxon-supervisor

The Jaxon classes: https://github.com/lagdo/jaxon-supervisor/tree/master/ajax
The Jaxon config: https://github.com/lagdo/jaxon-supervisor/blob/master/config/supervisor.php

#### A database admin

Forked from Adminer, and still being developed
https://github.com/lagdo/jaxon-dbadmin

The Jaxon classes: https://github.com/lagdo/jaxon-dbadmin/tree/main/app
The Jaxon config: https://github.com/lagdo/jaxon-dbadmin/blob/main/config/config.php

#### Tontine (african) management

Also a Laravel application
https://github.com/lagdo/tontine

The Jaxon classes: https://github.com/lagdo/tontine/tree/main/app/Ajax
The Jaxon config: https://github.com/lagdo/tontine/blob/main/config/jaxon.php

**Comment by feuzeu** [comment]
Hi,

The examples are fixed now.
Please keep in mind that they were designed to work with the version 2.x of the library. Today the version 5.0 is being prepared.
I've added a warning message.
