### ISSUE TITLE
Uncaught TypeError: Jaxon\Plugin\Request\CallableFunction\CallableFunction::configure(): Argument #2 ($sValue) must be of type string

### ISSUE THREAD

**Issue by hokascha** [jaxon-php/jaxon-core#113]
I am migrating from version 3. Was there any change in registering class methods as CallableFunctions? I am getting this error:

`Uncaught TypeError: Jaxon\Plugin\Request\CallableFunction\CallableFunction::configure(): Argument #2 ($sValue) must be of type string, page_login given, called in /vendor/jaxon-php/jaxon-core/src/Plugin/Request/CallableFunction/CallableFunctionPlugin.php on line 181 and defined in /vendor/jaxon-php/jaxon-core/src/Plugin/Request/CallableFunction/CallableFunction.php:113
`
The given `page_login` is the class name of the class of which a method is being registered by using:

`$jaxon->register(Jaxon::CALLABLE_FUNCTION, 'doLogout', ["class" => &$this]);`

What's wrong?

**Comment by feuzeu** [comment]
Hi,

Starting from version 3, it is recommended to register class names instead of instances.
It was enforced in version 4, where the registration function requires a string as parameter. Hence your error.

I suggest to move your ajax functions to separate classes which you will register with Jaxon and call in the browser.

In the specific case of the logout function, you don't really need Jaxon or ajax.
A route in your framework to the logout function can do the job.
