### ISSUE TITLE
Encode the response to utf-8 before calling json_encode()

### ISSUE THREAD

**Issue by jatubio** [jaxon-php/jaxon-core#18]
If the response commands have strings encoded in with a different encoding of utf-8. The method `Response\Response-getOutput()` fails silently because of the call to json_encode(), and return a null value instead a json.

Putting `$jaxon->setOption('core.decode_utf8',true);`  does not seems to solve the problem

**Comment by feuzeu** [comment]
I suggest you to convert the strings into utf-8 before adding them to the response.
Changing the encoding of the whole response is not a good idea because it can contain many strings, potentially with different encodings. So the simplest solution is to make sure you are using the correct encoding before adding a string into the response.

**Comment by jatubio** [comment]
Ok, thank you.

**Comment by Waxter81** [comment]
I've same problem, and I solved editing getOutput() method in Response Class, converting each Command string to UTF-8 with a new private function defined in the Class:

```
        foreach($this->aCommands as $xCommand)
        {
        	if($this->getOption('core.encoding') == 'ISO-8859-1') {
        		$response['jxnobj'][] = utf8_converter($xCommand);
        	}
        	else $response['jxnobj'][] = $xCommand;
        }   
```


```
    private function utf8_converter($mArg)
    {
    	if(is_array($mArg)) {
    		array_walk_recursive($mArg, function(&$item, $key){
    			$item = utf8_encode($item);    			
    		});
    	}
    	elseif(is_string($mArg))
    	{
    		$array = utf8_encode($mArg);
    	}
    	
    	return $mArg;
    }
```

I've opted for this solution because in Xajax there was not necessary to encode manually all strings before adding them to the response. This way it's easier for me to migrate from Xajax to Jaxon.
