### ISSUE TITLE
Your opinions about file upload

### ISSUE THREAD

**Issue by feuzeu** [jaxon-php/jaxon-core#23]
Hi All,
I've started implementing Ajax file upload in the library, and I need help to have the feature tested on various browsers, and I also need opinions about the feature, and the support of older browsers.

I've managed to make the feature as simple as possible, and here's how it works.
First of all, the id of the input file field is passed to Jaxon when registering the PHP class or function that will handle the uploaded file. The uploaded file in the above example is processed by the `Upload::saveFile()` method.
```
jaxon()->setOption('upload.default.dir', '/dir/where/to/save/uploaded/files');
jaxon()->register(Jaxon::CALLABLE_OBJECT, new Upload(), array(
    'saveFile' => array('upload' => "'input-file-id'"),
));
```
When the corresponding js function will be called in the browser, Jaxon will upload the files and save them in a configured directory.
Then, the uploaded files are available in the Jaxon class using the `jaxon()->getUploadedFiles()` call which returns an array of [UploadedFile objects](https://github.com/jaxon-php/jaxon-core/blob/master/src/Request/Support/UploadedFile.php).
```
class Upload
{
  public function saveFile()
  {
    $response = new Response;
    $uploadedFiles = jaxon()->getUploadedFiles();
    // Do anything necessary with the uploaded files
    return $response;
  }
}
```
For this code to work, you will need to install the master branches of both the jaxon-js and the jaxon-core libraries. They have not been tagged yet.

This code will work only if the js FormData object is implemented in the browser. This raises a question about the support for older browsers which may not have the js FormData object available, which is usually implemented with iframes. In your opinion, is it a strong requirement to have older browsers supported with this feature?

Thanks for your help.

**Comment by JohnnyQQQQ** [comment]
@feuzeu 

As far as I saw on [Can I Use](https://caniuse.com/#search=FormData) this feature would only be restricted in  < IE 10. I don't think this should be a big deal as IE 9 is already EOL.

At my current company we are migrating from xajax to jaxon right now for php-7 support and we are using iframes right now for uploading data from legacy browsers like IE9. So we would only make the switch as soon as we can drop the support for legacy browsers.

Perhaps you can rollout this feature as a plugin or some kind of addon to the core project. Otherwise you could write down a compatibility table in the `README.md` for certain features like this one. This would clarify things.

**Comment by feuzeu** [comment]
@JohnnyQQQQ

I've checked other js packages for Ajax file upload, and most of them fallback to iframe for legacy browsers. So I did the same.
Starting from version 2.1.0, Jaxon implements file upload in its core, with support for older browsers.

**Comment by feuzeu** [comment]
Here's the documentation of the upload feature.
https://www.jaxon-php.org/docs/requests/upload.html
