### ISSUE TITLE
How to set properties of a response object

### ISSUE THREAD

**Issue by DetsCastelli** [jaxon-php/jaxon-core#67]
I have upgraded to Version 3.2 of jaxon and saw that registering a CALLABLE_OBJECT isn't possible any longer.
In my code I use descendants of the Response-Object with some properties that needed to be set (depending on the page where they are used) and now I don't know how to do this.

**Comment by feuzeu** [comment]
Hi,
Since version 3, you do not register object anymore. You have to register classes, which are instantiated only when they are called.
If you need to initialize a Jaxon class, you can use the `init` callback.
```php
$jaxon->callback()->init(function($instance) {
    $instance->property = 'value';
});
```
You can also use dependency injection to pass objects as parameter to your Jaxon class constructor.
https://www.jaxon-php.org/docs/v3x/advanced/dependency-injection.html

**Comment by feuzeu** [comment]
I the above response doesn't answer your question, post a sample code of what you did before, so I can show you how to convert it to the new version.

**Comment by DetsCastelli** [comment]
Thanx, now it works for me. But I think it would be helpful if there's an example in the documentation
